// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMag9quBRXfM_DTbTh8USUWFEJOcmiDfA',
    appId: '1:496984282529:web:1ed01cb3fd2a620f4a67e0',
    messagingSenderId: '496984282529',
    projectId: 'katenadashboa',
    authDomain: 'katenadashboa.firebaseapp.com',
    storageBucket: 'katenadashboa.appspot.com',
    measurementId: 'G-B34QCVFNJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOI_B7WSMltuW21boSxic84fqHK4-Clck',
    appId: '1:496984282529:android:5de07cdcf644decc4a67e0',
    messagingSenderId: '496984282529',
    projectId: 'katenadashboa',
    storageBucket: 'katenadashboa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYv3S821syZVs5PNiXjHs9X0K0-kAfM8Y',
    appId: '1:496984282529:ios:aa2eacdceb7596d14a67e0',
    messagingSenderId: '496984282529',
    projectId: 'katenadashboa',
    storageBucket: 'katenadashboa.appspot.com',
    iosBundleId: 'com.example.katenaDashboard',
  );
}
